# Change 20/Jul/2022 by Daniel Weber
# Changed Fedora to basebuildcorbaplayground image
# removed installation of omniOrb and shifted it to above image
FROM basebuildcorbaplayground

CMD [ "/usr/local/bin/omniNames", "-start", "-logdir", "/var/log/omniORB" ]
