name: Corba

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ls
      run: echo `ls`
    - name: pwd 
      run: echo `pwd`
    - name: goto external
      run: cd external
    - name: pwd 
      run: echo `pwd`
    - name: ls
      run: echo `ls`
    - name: configure
      run: ./configure
