name: Corba

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: echo `ls`
    - name: ls
      run: cd external/omniORB-4.3.0 && 
           mkdir build &&
           cd build &&
           ../configure &&
           make 
