name: Corba

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
        
    - name: Cache External
      id: cache-external
      uses: actions/cache@v3
      with:
        path: external
        key: ${{ runner.os }}-external

    - name: External dependencies
      if: steps.cache-external.outputs.cache-hit != 'true'
      run: cd external/omniORB-4.3.0 && 
           mkdir build &&
           cd build &&
           ../configure &&
           make 
